version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=185.180.2.24
      - DB_USERNAME=437349_mysql_db
      - DB_PASSWORD=437349_mysql_p4s5
      - DB_NAME=437349_mysql_db
      - TIMEZONE=UTC
      - ERROR_REPORTING=1
    volumes:
      - ./src:/var/www/html
